version: 2
jobs:
  build:
    working_directory: ~/tsickle
    docker:
      - image: angular/ngcontainer:0.0.1
    steps:
      - checkout
      - restore_cache:
          key: tsickle-{{ checksum "yarn.lock" }}
      - run: bazel run @yarn//:yarn
      - run: bazel build ...
      - save_cache:
          key: tsickle-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
